spring:
  profiles:
    active: dev
  application:
    name: micro-web
  redis:
    host: localhost
dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.microweb
  consumer:
    timeout: 30000
    retries: 0
    check: false
server:
  port: 8000
  servlet:
    context-path: /api

logging:
  level:
    com:
      microweb:
        controller: info
p2p:
  alisms:
    access-key-id: ${p2p.aliSms.access-key-id}
    access-key-secret: ${p2p.aliSms.access-key-secret}
    endpoint: ${p2p.aliSms.endpoint}
  aliidcard:
    appcode: 09783177d13c42ef92793f1e9523e598