spring:
  application:
    name: micro-web
  redis:
    host: localhost
dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.microweb
  consumer:
    timeout: 30000
    retries: 0
    check: false
server:
  port: 8000
  servlet:
    context-path: /api

logging:
  level:
    com:
      microweb:
        controller: info